language: node_js

node_js:
  - '10'
  - '11'
  - '8'
  - '6'

cache:
  directories:
  - node_modules
sudo: false

script:
- yarn test && yarn build

notifications:
  email:
    on_success: never
    on_failure: never
